### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

### ISSUE THREAD

**Issue by raphaelhuleux** [Zettelkasten-Method/atom-wikilink#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.6
**Thrown From**: [wikilink](https://github.com/xHN35RQ/atom-wikilink) package 0.14.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getCursorBufferPosition' of undefined

```
At /Users/raphaelhuleux/.atom/packages/wikilink/lib/wikilink.coffee:62

TypeError: Cannot read property 'getCursorBufferPosition' of undefined
    at Object.follow (/packages/wikilink/lib/wikilink.coffee:62:29)
    at /packages/wikilink/lib/wikilink.coffee:35:83)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349781)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348256)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725974)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:733897)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -1:40.3.0 core:backspace (input.hidden-input)
     -0:12.3.0 wikilink:follow (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
wikilink 0.14.0 
```

**Comment by DivineDominion** [comment]
I've upgraded the package today with another fix. I'll have to wait for someone else to step up and fix this error though, because I don't use Atom or the plugins myself.

**Comment by theshoals** [comment]
I was able to reproduce the TypeError with the following steps:
1 - File > New Window
2 - Close the new document that gets created to leave a blank workspace
3 - Packages > wikilink > Follow Link

https://github.com/atom/atom/issues/12702 suggests that this bug could also be triggered by trying to follow a link in a non-PaneItem editor.

**Comment by raphaelhuleux** [comment]
Thank you!

I have another question. I realized that if my note are in a sub folder of a project (let’s say notes/zettelkasten), then clicking the wiki links won’t work and they will create new notes in the “notes” folder instead. For the wiki links to work, the project has to be the folder “zettelkasten”. Do you think this will be
changed in the future ?

Regards

Raphael

**Comment by theshoals** [comment]
> Thank you! I have another question. I realized that if my note are in a sub folder of a project (let’s say notes/zettelkasten), then clicking the wiki links won’t work and they will create new notes in the “notes” folder instead. For the wiki links to work, the project has to be the folder “zettelkasten”. Do you think this will be changed in the future ?

The wikilink package assumes that all links are relative to the project directory (https://github.com/Zettelkasten-Method/atom-wikilink/issues/4).  It seems like it would be possible to add a config that allows users to specify the base directory of the notes on a global basis.

Edit: https://github.com/Zettelkasten-Method/atom-wikilink/issues/8 seems to be requesting the ability for a link to be relative to the path of the current file (the file where the link appears).  That seems like a better config approach than a global directory.

**Comment by DivineDominion** [comment]
As for "is this possible" -- I'm not philosophically opposed to a configuration that would allow relative paths. I don't use them myself, but why not. Am open for Prs 👍

**Comment by theshoals** [comment]
https://github.com/Zettelkasten-Method/atom-wikilink/pull/14 adds a new "Link Resolution" config option to support the relative-path use case (the old behavior remains the default).
