### ISSUE TITLE
2 links within a line

### ISSUE THREAD

**Issue by raphaelhuleux** [Zettelkasten-Method/atom-wikilink#15]
Hello,

When I'm creating two links within a sentence (i.e. line), such as  "something something [[link]] something something [[link2]]", the link first delimiter will not be recognized and clicking on the first link will create a new note called
" [[link]] something something [[link2" instead of redirecting to [[link]].

**Comment by theshoals** [comment]
Good catch.  I submitted a PR to address this issue: https://github.com/Zettelkasten-Method/atom-wikilink/pull/16
