### ISSUE TITLE
wikilink:follow follows wrong path

### ISSUE THREAD

**Issue by noizhardware** [Zettelkasten-Method/atom-wikilink#8]
in file R:\s\c\epiphania\database\matrixmixers.md: `[[features]]`

* Expected behavior:
  follows the file R:\s\c\epiphania\database\features.md 

* Experienced behavior:
  follows the file R:\s\features.md

In other cases the plugin works just fine.

OS: Windows 10 Pro 64-bit (10.0, Build 17763)
npm: 6.14.4
Atom: 1.47.0
Electron: 5.0.13
Chrome: 73.0.3683.121
Node: 12.0.0

**Comment by DivineDominion** [comment]
Thanks for reporting this!

You wouldn't know how to approach a fix, by chance? The commands in the follow command look innocent enough to me :)
https://github.com/Zettelkasten-Method/atom-wikilink/blob/master/lib/wikilink.coffee#L59

**Comment by noizhardware** [comment]
> You wouldn't know how to approach a fix, by chance?

had a look, but sorry, I'm not familiar with .coffee or the framework

One thing I noticed, the error occours whenever the files are in a folder with depth > 1.
So in `C:/folder/file.md` will work, in `C:/folder/otherfolder/file.md` will not, following a link with depth 1, `C:/folder/file.md`.

It seems to always fall back to depth 1, regardless of the original folder depth. 
So `C:/folder/anotherfolder/yesafolder/foldyeah/another/file.md` will also result in `C:/folder/file.md`

I don't know how this translates into a solution to the problem, but seems to be an important clue.

**Comment by theshoals** [comment]
The wikilink package assumes that all links are relative to the _project_ directory (https://github.com/Zettelkasten-Method/atom-wikilink/issues/4).

For this use case to work, the package would have to introduce a config that makes links relative to the current file.  https://github.com/Zettelkasten-Method/atom-wikilink/issues/10#issuecomment-673283291 has a similar request.

**Comment by theshoals** [comment]
https://github.com/Zettelkasten-Method/atom-wikilink/pull/14 adds a new "Link Resolution" config option to support this use case (the old behavior remains the default).
